package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5"
	"github.com/jokull/onwardpg/internal/protocol"
)

func TestDevelopmentAndDiffAlignLiveOnlyIgnoreReceiptsOnPostgreSQL(t *testing.T) {
	adminURL := os.Getenv("ONWARDPG_TEST_DATABASE_URL")
	if adminURL == "" {
		t.Skip("ONWARDPG_TEST_DATABASE_URL is not set")
	}
	liveURL, cleanup := createTestDatabase(t, adminURL)
	defer cleanup()
	t.Setenv("ONWARDPG_IGNORE_DEV_URL", liveURL)
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, liveURL)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close(ctx)
	const ddl = `CREATE TABLE public.items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL);`
	if _, err := conn.Exec(ctx, ddl+`
CREATE TABLE public.django_migrations (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, app varchar(255) NOT NULL, name varchar(255) NOT NULL, applied timestamptz NOT NULL);
INSERT INTO public.items (name) VALUES ('retained');
INSERT INTO public.django_migrations (app, name, applied) VALUES ('app', '0001_initial', now());`); err != nil {
		t.Fatal(err)
	}
	repository := t.TempDir()
	writeTestFile(t, repository, "schema.sql", ddl)
	const selector = "table:public.django_migrations"
	for _, mode := range []string{"workspace", "strict"} {
		t.Run("development "+mode, func(t *testing.T) {
			writeTestFile(t, repository, ".onwardpg.toml", fmt.Sprintf(`version = 1
bundle_root = "onward-bundles"
[targets.primary]
schema_file = "schema.sql"
scratch_database_env = "ONWARDPG_TEST_DATABASE_URL"
dev_database_env = "ONWARDPG_IGNORE_DEV_URL"
dev_mode = %q
ignore = ["table:public.django_migrations"]
`, mode))
			result := captureStdout(t, func() int { return runDevAt([]string{"plan"}, repository) })
			var report struct {
				Status             string   `json:"status"`
				Changed            bool     `json:"changed"`
				CurrentFingerprint string   `json:"current_fingerprint"`
				DesiredFingerprint string   `json:"desired_fingerprint"`
				Ignored            []string `json:"ignored"`
			}
			if err := json.Unmarshal([]byte(result.stdout), &report); err != nil {
				t.Fatal(err)
			}
			if result.code != 0 || report.Status != "no_changes" || report.Changed || report.CurrentFingerprint == "" || report.CurrentFingerprint != report.DesiredFingerprint || !reflect.DeepEqual(report.Ignored, []string{selector}) {
				t.Fatalf("development comparison: %d %s", result.code, result.stdout)
			}
			result = captureStdout(t, func() int {
				return runDevAt([]string{"plan", "--ignore", "table:public.django_migrationz"}, repository)
			})
			if result.code == 0 || !strings.Contains(result.stdout, "unused ignore selectors") {
				t.Fatalf("explicit typo accepted: %d %s", result.code, result.stdout)
			}
		})
	}
	for _, hints := range []bool{false, true} {
		t.Run(fmt.Sprintf("diff semantic hints %t", hints), func(t *testing.T) {
			args := []string{"--from", liveURL, "--to", "file://" + filepath.Join(repository, "schema.sql"), "--dev-url", adminURL, "--ignore", selector}
			if hints {
				writeTestFile(t, repository, "hints.json", "[]")
				args = append(args, "--hints-file", filepath.Join(repository, "hints.json"))
			}
			result := captureStdout(t, func() int { return runLowLevelPlan("diff", args) })
			var report protocol.Result
			if err := json.Unmarshal([]byte(result.stdout), &report); err != nil {
				t.Fatal(err)
			}
			if result.code != 0 || report.Status != protocol.Planned || len(report.Statements) != 0 || report.CurrentFingerprint != report.DesiredFingerprint || !reflect.DeepEqual(report.Ignored, []string{selector}) {
				t.Fatalf("diff comparison: %d %s", result.code, result.stdout)
			}
			args[7] = "table:public.django_migrationz"
			result = captureStdout(t, func() int { return runLowLevelPlan("diff", args) })
			if result.code == 0 || !strings.Contains(result.stdout, "unused ignore selectors") {
				t.Fatalf("explicit typo accepted: %d %s", result.code, result.stdout)
			}
		})
	}
	var appRows, journalRows int
	if err := conn.QueryRow(ctx, "SELECT (SELECT count(*) FROM public.items), (SELECT count(*) FROM public.django_migrations)").Scan(&appRows, &journalRows); err != nil {
		t.Fatal(err)
	}
	if appRows != 1 || journalRows != 1 {
		t.Fatalf("comparison changed caller data: app=%d journal=%d", appRows, journalRows)
	}
}
