package main

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jokull/onwardpg/internal/bundle"
	"github.com/jokull/onwardpg/internal/contractcheck"
	"github.com/jokull/onwardpg/internal/workspace"
	"github.com/jokull/onwardpg/pgschema"
)

func TestConfiguredJournalIgnoreSurvivesPlanningAndContractOnPostgreSQL(t *testing.T) {
	adminURL := os.Getenv("ONWARDPG_TEST_DATABASE_URL")
	if adminURL == "" {
		t.Skip("ONWARDPG_TEST_DATABASE_URL is not set")
	}
	liveURL, cleanup := createTestDatabase(t, adminURL)
	defer cleanup()
	t.Setenv("ONWARDPG_JOURNAL_LIVE_URL", liveURL)
	ctx := context.Background()
	conn, err := pgx.Connect(ctx, liveURL)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close(ctx)
	baseline := `CREATE TABLE public.items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL, legacy text);`
	if _, err := conn.Exec(ctx, baseline+`
CREATE TABLE public.django_migrations (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, app varchar(255) NOT NULL, name varchar(255) NOT NULL, applied timestamptz NOT NULL);
INSERT INTO public.items (name, legacy) VALUES ('retained', 'old');
INSERT INTO public.django_migrations (app, name, applied) VALUES ('app', '0001_initial', now());`); err != nil {
		t.Fatal(err)
	}
	t.Run("observer wildcard binds only observed exact objects", func(t *testing.T) {
		planning := pgschema.New()
		if err := planning.AddIgnored("table:public.items"); err != nil {
			t.Fatal(err)
		}
		selectors, err := workspace.ObserverIgnoreSelectors(ctx, workspace.Target{DevDatabaseEnv: "ONWARDPG_JOURNAL_LIVE_URL", Ignore: []string{"table:*"}}, planning)
		if err != nil {
			t.Fatal(err)
		}
		if !reflect.DeepEqual(selectors, []string{"table:public.django_migrations"}) {
			t.Fatalf("wildcard observer policy widened: %#v", selectors)
		}
	})
	repository := t.TempDir()
	config := `version = 1
bundle_root = "onward-bundles"
[targets.primary]
schema_file = "schema.sql"
scratch_database_env = "ONWARDPG_TEST_DATABASE_URL"
dev_database_env = "ONWARDPG_JOURNAL_LIVE_URL"
dev_mode = "workspace"
ignore = ["table:public.django_migrations"]
`
	writeTestFile(t, repository, ".onwardpg.toml", config)
	writeTestFile(t, repository, "schema.sql", baseline)
	t.Run("command ignore remains strict", func(t *testing.T) {
		result := captureStdout(t, func() int { return runInitAt([]string{"--ignore", "table:public.django_migrationz"}, repository) })
		if result.code == 0 || !strings.Contains(result.stdout, "unused ignore selectors") {
			t.Fatalf("explicit typo accepted: %d %s", result.code, result.stdout)
		}
	})
	t.Run("configured typo rejected without receipt", func(t *testing.T) {
		writeTestFile(t, repository, ".onwardpg.toml", strings.ReplaceAll(config, "django_migrations", "django_migrationz"))
		defer writeTestFile(t, repository, ".onwardpg.toml", config)
		result := captureStdout(t, func() int { return runInitAt(nil, repository) })
		if result.code == 0 || !strings.Contains(result.stdout, "unused ignore selectors") {
			t.Fatalf("configured typo accepted: %d %s", result.code, result.stdout)
		}
		if _, err := os.Stat(filepath.Join(repository, "onward-bundles/primary/baseline/manifest.json")); !os.IsNotExist(err) {
			t.Fatalf("failed validation wrote manifest: %v", err)
		}
	})
	initialized := captureStdout(t, func() int { return runInitAt(nil, repository) })
	if initialized.code != 0 {
		t.Fatalf("init: %d %s", initialized.code, initialized.stdout)
	}
	checkReceipt := func(name string) bundle.Artifact {
		t.Helper()
		artifact, err := bundle.Read(filepath.Join(repository, "onward-bundles/primary", name))
		if err != nil {
			t.Fatal(err)
		}
		if len(artifact.Manifest.Planner.IgnoreSelectors) != 0 {
			t.Fatalf("live-only ignore leaked into clone policy: %#v", artifact.Manifest.Planner)
		}
		if !reflect.DeepEqual(artifact.Manifest.Planner.ObserverIgnoreSelectors, []string{"table:public.django_migrations"}) {
			t.Fatalf("observer policy missing: %#v", artifact.Manifest.Planner)
		}
		return artifact
	}
	checkReceipt("baseline")
	t.Run("drift ignores live journal but rejects typo", func(t *testing.T) {
		result := captureStdout(t, func() int {
			return runDriftAt([]string{"check", "--database", liveURL, "--ignore", "table:public.django_migrations"}, repository)
		})
		if result.code != 0 || !strings.Contains(result.stdout, `"status":"drift_free"`) {
			t.Fatalf("journal drift: %d %s", result.code, result.stdout)
		}
		result = captureStdout(t, func() int {
			return runDriftAt([]string{"check", "--database", liveURL, "--ignore", "table:public.django_migrationz"}, repository)
		})
		if result.code == 0 || !strings.Contains(result.stdout, "unused ignore selectors") {
			t.Fatalf("drift typo accepted: %d %s", result.code, result.stdout)
		}
	})
	hint := `{"kind":"drop","object":"column","name":["public","items","legacy"]}`
	// Avoid rename inference by making the additive column's type distinct.
	writeTestFile(t, repository, "schema.sql", strings.Replace(baseline, "legacy text", "note integer", 1))
	planned := captureStdout(t, func() int { return runWorkflowPlanAt([]string{"retire-legacy", "--hint", hint}, repository) })
	if planned.code != 0 {
		t.Fatalf("plan: %d %s", planned.code, planned.stdout)
	}
	artifact := checkReceipt("retire-legacy")
	verified := captureStdout(t, func() int { return runVerifyAt([]string{"--bundle", "retire-legacy"}, repository) })
	if verified.code != 0 {
		t.Fatalf("verify: %d %s", verified.code, verified.stdout)
	}
	phase, ok := artifact.Manifest.Phases["expand"]
	if !ok {
		t.Fatal("expected actual expand phase")
	}
	batches, err := bundle.ParsePhaseSQL(artifact.Files[phase.Path], phase.Transactional)
	if err != nil {
		t.Fatal(err)
	}
	for _, batch := range batches {
		if batch.Transactional {
			tx, err := conn.Begin(ctx)
			if err != nil {
				t.Fatal(err)
			}
			if _, err := tx.Exec(ctx, batch.SQL); err != nil {
				_ = tx.Rollback(ctx)
				t.Fatal(err)
			}
			if err := tx.Commit(ctx); err != nil {
				t.Fatal(err)
			}
		} else if _, err := conn.Exec(ctx, batch.SQL); err != nil {
			t.Fatal(err)
		}
	}
	now := time.Now().UTC()
	manifest := artifact.Manifest
	evidence := contractcheck.Evidence{Target: "primary", Environment: "test", PlanID: manifest.PlanID, BundleEntryDigest: manifest.History.EntryDigest, DesiredFingerprint: manifest.DesiredSource.Fingerprint, Generation: manifest.Generation, Release: "isolated-test", ObservedAt: now.Format(time.RFC3339), ExpiresAt: now.Add(time.Hour).Format(time.RFC3339)}
	for _, category := range []string{"web", "workers", "scheduled_jobs", "queues", "connection_pools", "previews", "ad_hoc_writers"} {
		evidence.Cohorts = append(evidence.Cohorts, contractcheck.Cohort{Category: category, Name: category, Status: "isolated", SourceKind: "manual", Source: "disposable regression database"})
	}
	body, err := json.Marshal(evidence)
	if err != nil {
		t.Fatal(err)
	}
	evidencePath := filepath.Join(repository, "readiness.json")
	if err := os.WriteFile(evidencePath, body, 0600); err != nil {
		t.Fatal(err)
	}
	check := func() (int, contractcheck.Report) {
		t.Helper()
		result := captureStdout(t, func() int {
			return runContractAt([]string{"check", "--environment", "test", "--database-env", "ONWARDPG_JOURNAL_LIVE_URL", "--evidence", evidencePath}, repository)
		})
		var report contractcheck.Report
		if err := json.Unmarshal([]byte(result.stdout), &report); err != nil {
			t.Fatalf("contract response: %s: %v", result.stdout, err)
		}
		return result.code, report
	}
	code, report := check()
	if code != 0 || report.Status != "ready" {
		t.Fatalf("contract readiness: %d %#v", code, report)
	}
	var journalRows, appRows int
	if err := conn.QueryRow(ctx, "SELECT (SELECT count(*) FROM public.django_migrations), (SELECT count(*) FROM public.items)").Scan(&journalRows, &appRows); err != nil {
		t.Fatal(err)
	}
	if journalRows != 1 || appRows != 1 {
		t.Fatalf("caller data changed: journal=%d app=%d", journalRows, appRows)
	}
	// A config edit cannot expand a previously bound observer policy.
	if _, err := conn.Exec(ctx, "CREATE TABLE public.unrelated (id integer)"); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, repository, ".onwardpg.toml", strings.Replace(config, `"table:public.django_migrations"]`, `"table:public.django_migrations", "table:public.unrelated"]`, 1))
	code, report = check()
	if code == 0 || len(report.Findings) == 0 || report.Findings[0].Code != "catalog_drift" {
		t.Fatalf("unbound config suppressed unrelated drift: %d %#v", code, report)
	}
}
