package testkit

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type Workspace struct {
	Root       string
	Target     string
	BundleRoot string
	SchemaPath string
	ScratchEnv string
}

func NewWorkspace(root, target, scratchEnv string) (*Workspace, error) {
	if root == "" || target == "" || scratchEnv == "" {
		return nil, fmt.Errorf("workspace root, target, and scratch environment are required")
	}
	workspace := &Workspace{
		Root: root, Target: target, BundleRoot: "migrations/onward",
		SchemaPath: filepath.Join(root, "schema.sql"), ScratchEnv: scratchEnv,
	}
	configuration := fmt.Sprintf(`version = 1
bundle_root = %q

[targets.%s]
schema_file = "schema.sql"
scratch_database_env = %q
`, workspace.BundleRoot, target, scratchEnv)
	if err := os.WriteFile(filepath.Join(root, ".onwardpg.toml"), []byte(configuration), 0o600); err != nil {
		return nil, fmt.Errorf("write workspace configuration: %w", err)
	}
	return workspace, nil
}

func (w *Workspace) WriteSchema(ddl []byte) error {
	if err := os.WriteFile(w.SchemaPath, ddl, 0o600); err != nil {
		return fmt.Errorf("write desired schema: %w", err)
	}
	return nil
}

func (w *Workspace) BundlePath(bundleID string) string {
	return filepath.Join(w.Root, filepath.FromSlash(w.BundleRoot), w.Target, bundleID)
}

func (w *Workspace) PhasePath(bundleID, phase string) string {
	return filepath.Join(w.BundlePath(bundleID), "phases", phase+".sql")
}

// RecordWorkspace copies the public artifacts generated by one acceptance
// journey into the optional CI evidence directory. Configuration contains
// environment-variable names, never database credentials.
func RecordWorkspace(root, label string) error {
	artifactRoot := os.Getenv("ONWARDPG_ACCEPTANCE_ARTIFACT_DIR")
	if artifactRoot == "" {
		return nil
	}
	label = sanitizeArtifactLabel(label)
	destinationRoot := filepath.Join(artifactRoot, "workspaces", label)
	return filepath.Walk(root, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		destination := filepath.Join(destinationRoot, relative)
		if info.IsDir() {
			return os.MkdirAll(destination, 0o700)
		}
		return copyArtifactFile(path, destination)
	})
}

func copyArtifactFile(sourcePath, destinationPath string) error {
	source, err := os.Open(sourcePath)
	if err != nil {
		return err
	}
	target, err := os.OpenFile(destinationPath, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
	if err != nil {
		_ = source.Close()
		return err
	}
	_, copyErr := io.Copy(target, source)
	sourceErr := source.Close()
	targetErr := target.Close()
	if copyErr != nil {
		return copyErr
	}
	if sourceErr != nil {
		return sourceErr
	}
	return targetErr
}

func sanitizeArtifactLabel(label string) string {
	var result strings.Builder
	for _, character := range strings.ToLower(label) {
		if character >= 'a' && character <= 'z' || character >= '0' && character <= '9' || character == '-' || character == '_' {
			result.WriteRune(character)
		} else {
			result.WriteByte('_')
		}
	}
	if result.Len() == 0 {
		return "acceptance"
	}
	return result.String()
}
