package source

import (
	"context"
	"fmt"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jokull/onwardpg/pgschema"
)

func TestLoadGraphIgnoresDjangoJournalAndOwnedMetadata(t *testing.T) {
	url := os.Getenv("ONWARDPG_TEST_DATABASE_URL")
	if url == "" {
		t.Skip("set ONWARDPG_TEST_DATABASE_URL to run PostgreSQL integration tests")
	}
	ctx := context.Background()
	admin, err := pgx.Connect(ctx, url)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close(ctx)
	database := fmt.Sprintf("onwardpg_table_ignore_%d", time.Now().UnixNano())
	if _, err := admin.Exec(ctx, "CREATE DATABASE "+quote(database)); err != nil {
		t.Fatal(err)
	}
	defer func() { _, _ = admin.Exec(ctx, "DROP DATABASE "+quote(database)+" WITH (FORCE)") }()
	config := admin.Config().Copy()
	config.Database = database
	conn, err := pgx.ConnectConfig(ctx, config)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close(ctx)
	if _, err := conn.Exec(ctx, `
CREATE TABLE public.django_migrations (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 app varchar(255) NOT NULL,
 name varchar(255) NOT NULL,
 applied timestamptz NOT NULL
);
CREATE TABLE public.application_items (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL);
`); err != nil {
		t.Fatal(err)
	}
	const selector = "table:public.django_migrations"
	inspect := func(t *testing.T) *pgschema.Snapshot {
		t.Helper()
		snapshot, err := inspectGraphConfig(ctx, config, []string{selector}, true)
		if err != nil {
			t.Fatal(err)
		}
		if got := snapshot.Ignored(); !reflect.DeepEqual(got, []string{selector}) {
			t.Fatalf("ignore receipt = %#v", got)
		}
		if got := snapshot.Unsupported(); len(got) != 0 {
			t.Fatalf("unsupported state = %#v", got)
		}
		for _, object := range snapshot.Objects() {
			id := object.ObjectID()
			if id.Schema == "public" && id.Name == "django_migrations" {
				t.Fatalf("ignored journal object retained: %s", id)
			}
		}
		app := (pgschema.Table{Schema: "public", Name: "application_items"}).ObjectID()
		for _, id := range []pgschema.ID{app,
			(pgschema.Column{Table: app, Name: "id"}).ObjectID(),
			(pgschema.Column{Table: app, Name: "name"}).ObjectID(),
			(pgschema.Constraint{Table: app, Name: "application_items_pkey"}).ObjectID(),
			(pgschema.Index{Table: app, Name: "application_items_pkey"}).ObjectID(),
			(pgschema.ReplicaIdentity{Table: app}).ObjectID(),
		} {
			if _, ok := snapshot.Object(id); !ok {
				t.Fatalf("application object missing: %s", id)
			}
		}
		return snapshot
	}
	t.Run("Django identity primary key journal", func(t *testing.T) { inspect(t) })
	if _, err := conn.Exec(ctx, `
ALTER TABLE public.django_migrations ADD CONSTRAINT journal_unique UNIQUE (app, name);
ALTER TABLE public.django_migrations ADD CONSTRAINT journal_check CHECK (app <> '');
CREATE FUNCTION public.touch_row() RETURNS trigger LANGUAGE plpgsql AS 'BEGIN RETURN NEW; END';
CREATE TRIGGER touch_row BEFORE UPDATE ON public.django_migrations FOR EACH ROW EXECUTE FUNCTION public.touch_row();
CREATE TRIGGER touch_row BEFORE UPDATE ON public.application_items FOR EACH ROW EXECUTE FUNCTION public.touch_row();
ALTER TABLE public.django_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.application_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY readable ON public.django_migrations FOR SELECT USING (id > 0);
CREATE POLICY readable ON public.application_items FOR SELECT USING (id > 0);
GRANT SELECT ON public.django_migrations, public.application_items TO PUBLIC;
ALTER TABLE public.django_migrations REPLICA IDENTITY USING INDEX django_migrations_pkey;
`); err != nil {
		t.Fatal(err)
	}
	t.Run("owned metadata", func(t *testing.T) {
		snapshot := inspect(t)
		app := (pgschema.Table{Schema: "public", Name: "application_items"}).ObjectID()
		for _, object := range []pgschema.Object{
			pgschema.Trigger{Table: app, Name: "touch_row"},
			pgschema.Policy{Table: app, Name: "readable"},
			pgschema.RowSecurity{Table: app},
			pgschema.TablePrivilege{Table: app, Grantee: "PUBLIC", Privilege: "SELECT"},
			pgschema.Routine{Schema: "public", Name: "touch_row"},
		} {
			if _, ok := snapshot.Object(object.ObjectID()); !ok {
				t.Fatalf("unrelated object missing: %s", object.ObjectID())
			}
		}
	})
	t.Run("unmodeled table still fails", func(t *testing.T) {
		tx, err := conn.BeginTx(ctx, pgx.TxOptions{AccessMode: pgx.ReadOnly})
		if err != nil {
			t.Fatal(err)
		}
		defer tx.Rollback(ctx)
		tracker, err := newIgnoreTracker([]string{selector})
		if err != nil {
			t.Fatal(err)
		}
		err = inspectGraphReplicaIdentities(ctx, tx, pgschema.New(), tracker)
		if err == nil || !strings.Contains(err.Error(), "replica identity table table:public:application_items is missing from graph") {
			t.Fatalf("missing table error = %v", err)
		}
	})
	t.Run("unmodeled metadata owners still block", func(t *testing.T) {
		tx, err := conn.BeginTx(ctx, pgx.TxOptions{AccessMode: pgx.ReadOnly})
		if err != nil {
			t.Fatal(err)
		}
		defer tx.Rollback(ctx)
		for _, test := range []struct {
			name     string
			inspect  func(context.Context, pgx.Tx, *pgschema.Snapshot, *ignoreTracker) error
			prefixes []string
		}{
			{"triggers", inspectGraphTriggers, []string{"trigger_table:"}},
			{"policies and row security", inspectGraphPolicies, []string{"policy_table:", "row_security_table:"}},
			{"privileges", inspectGraphTablePrivileges, []string{"table_privilege_table:"}},
		} {
			t.Run(test.name, func(t *testing.T) {
				tracker, err := newIgnoreTracker([]string{selector})
				if err != nil {
					t.Fatal(err)
				}
				snapshot := pgschema.New()
				if err := test.inspect(ctx, tx, snapshot, tracker); err != nil {
					t.Fatal(err)
				}
				for _, prefix := range test.prefixes {
					found := false
					for _, blocker := range snapshot.Unsupported() {
						if strings.HasPrefix(blocker, prefix) && strings.Contains(blocker, "django_migrations") {
							found = true
						}
					}
					if !found {
						t.Fatalf("missing %s blocker: %#v", prefix, snapshot.Unsupported())
					}
				}
			})
		}
	})
	t.Run("scoped serial journal retains schema and standalone sequence", func(t *testing.T) {
		if _, err := conn.Exec(ctx, `CREATE SCHEMA drizzle;
CREATE TABLE drizzle.__drizzle_migrations (id serial PRIMARY KEY, hash text NOT NULL, created_at bigint);
CREATE SEQUENCE drizzle.unrelated_sequence;`); err != nil {
			t.Fatal(err)
		}
		selectors := []string{selector, "table:drizzle.__drizzle_migrations"}
		snapshot, err := inspectGraphConfig(ctx, config, selectors, true)
		if err != nil {
			t.Fatal(err)
		}
		for _, object := range []pgschema.Object{pgschema.Schema{Name: "drizzle"}, pgschema.Sequence{Schema: "drizzle", Name: "unrelated_sequence"}} {
			if _, ok := snapshot.Object(object.ObjectID()); !ok {
				t.Fatalf("table ignore silently removed %s", object.ObjectID())
			}
		}
		if _, ok := snapshot.Object((pgschema.Table{Schema: "drizzle", Name: "__drizzle_migrations"}).ObjectID()); ok {
			t.Fatal("scoped journal retained")
		}
		selectors = append(selectors, "schema:drizzle", "sequence:drizzle.unrelated_sequence")
		snapshot, err = inspectGraphConfig(ctx, config, selectors, true)
		if err != nil {
			t.Fatal(err)
		}
		if len(snapshot.Ignored()) != len(selectors) {
			t.Fatalf("explicit boundary receipt = %#v", snapshot.Ignored())
		}
	})
	t.Run("ignored replica index still fails", func(t *testing.T) {
		_, err := inspectGraphConfig(ctx, config, []string{"index:public.django_migrations.django_migrations_pkey"}, true)
		if err == nil || !strings.Contains(err.Error(), "replica identity index index:public:django_migrations:django_migrations_pkey is missing from graph") {
			t.Fatalf("missing index error = %v", err)
		}
	})
	t.Run("incoming application foreign key requires explicit exclusion", func(t *testing.T) {
		if _, err := conn.Exec(ctx, `ALTER TABLE public.application_items ADD CONSTRAINT journal_reference FOREIGN KEY (id) REFERENCES public.django_migrations (id)`); err != nil {
			t.Fatal(err)
		}
		_, err := inspectGraphConfig(ctx, config, []string{selector}, true)
		if err == nil || !strings.Contains(err.Error(), "references ignored table") {
			t.Fatalf("incoming application dependency disappeared: %v", err)
		}
		if _, err := inspectGraphConfig(ctx, config, []string{selector, "constraint:public.application_items.journal_reference"}, true); err != nil {
			t.Fatal(err)
		}
	})

}
