-- onwardpg: forward-only PostgreSQL migration plan.
-- Review every batch, safety classification, and hazard in the JSON plan before execution.
-- ============================================================================
-- CONTRACT — run after pre-deployment instances, workers, pools, and queues have drained.
-- The one newly deployed application version must work before and after every batch below.
-- Catch-up, validation, enforcement, and compatibility cleanup belong here.
-- ============================================================================
-- onwardpg:batch transactional
-- Batch batch-contract-001: transactional.
-- Review: safety=manual; hazards=manual_sql,table_rewrite_possible,access_exclusive_lock,single_deployment_bridge_required; requires_gates=writers:legacy.
-- onwardpg:edit begin stmt-sha256-44676ce9e707f66833991a1a735aef1a5a0d625711608162c55dbfac508604b7
-- ONWARDPG TODO: replace this comment with reviewed CONTRACT SQL for column:app:accounts:age (text -> integer).
-- After pre-deployment writers drain, perform final catch-up/assertions, remove compatibility objects, and converge to PostgreSQL type integer.
-- Required mutation shape: convert "app"."accounts"."age" to integer with a reviewed expression; do not rely on an inferred cast.
-- Include blocking Boolean assertions in this pocket for every data-dependent conversion assumption; onwardpg verification executes this exact SQL.
-- onwardpg:edit end stmt-sha256-44676ce9e707f66833991a1a735aef1a5a0d625711608162c55dbfac508604b7
-- Review: safety=review; hazards=type_change_statistics_refresh,database_performance_impact; requires_gates=writers:legacy.
ANALYZE "app"."accounts" ("age");
