-- onwardpg: forward-only PostgreSQL migration plan.
-- Review every batch, safety classification, and hazard in the JSON plan before execution.
-- ============================================================================
-- CONTRACT — run after pre-deployment instances, workers, pools, and queues have drained.
-- The one newly deployed application version must work before and after every batch below.
-- Catch-up, validation, enforcement, and compatibility cleanup belong here.
-- ============================================================================
-- onwardpg:batch transactional
-- Batch batch-contract-001: transactional.
-- Review: safety=manual; hazards=manual_sql,table_rewrite_possible,access_exclusive_lock,single_deployment_bridge_required; requires_gates=writers:legacy.
-- onwardpg:edit begin stmt-sha256-d8f3d897e34cdfb771ae8eb7c6ed431dc41a8f757c8e14233974fca504f73108
-- ONWARDPG TODO: replace this comment with reviewed CONTRACT SQL for column:app:accounts:age (text -> integer).
-- After pre-deployment writers drain, perform final catch-up/assertions, remove compatibility objects, and converge to PostgreSQL type integer.
-- Required mutation shape: convert "app"."accounts"."age" to integer with a reviewed expression; do not rely on an inferred cast.
-- Add boolean assertions to verify.sql for every data-dependent conversion assumption.
-- onwardpg:edit end stmt-sha256-d8f3d897e34cdfb771ae8eb7c6ed431dc41a8f757c8e14233974fca504f73108
-- Review: safety=review; hazards=type_change_statistics_refresh,database_performance_impact; requires_gates=writers:legacy.
ANALYZE "app"."accounts" ("age");
